Kmer count: build pass

diff --git a/examples/kcount/src/Makefile b/examples/kcount/src/Makefile
--- a/examples/kcount/src/Makefile
+++ b/examples/kcount/src/Makefile
@@ -2,7 +2,8 @@ SHELL='bash'
 
 # Modify ARLROOT if you want to move this Makefile
 # out of current directory.
-ARLROOT=$(PWD)/../
+ARLROOT=$(PWD)/../../../
+KCOUNTFLAG=-I$(PWD)/../include/ -I$(PWD)/zstr/src/ -lz
 
 PLATFORM = $(shell echo $(HOSTNAME) | tr '[:lower:]' '[:upper:]')
 
@@ -19,7 +20,7 @@ include $(gasnet_prefix)/include/mpi-conduit/mpi-par.mak
 CXX = mpic++
 endif
 
-ARLFLAGS = -lpthread $(GASNET_CXXCPPFLAGS) $(GASNET_CXXFLAGS) $(GASNET_LDFLAGS) $(GASNET_LIBS) -DGASNET_EX -I$(ARLROOT)
+ARLFLAGS = -lpthread $(GASNET_CXXCPPFLAGS) $(GASNET_CXXFLAGS) $(GASNET_LDFLAGS) $(GASNET_LIBS) -DGASNET_EX -I$(ARLROOT) $(KCOUNTFLAG)
 
 CXXFLAGS = -std=gnu++17 $(ARLFLAGS)
 
@@ -37,7 +38,7 @@ TEST_RUN=mpirun -n 4
 test: all
 	@for target in $(TARGETS) ; do \
 		echo "R $$target $(BACKEND)" ;\
-  	time $(TEST_RUN) ./$$target || (echo "$$target $(BACKEND) FAIL $$?"; exit 1) ;\
+  	time $(TEST_RUN) ./$$target || (echo "$$target $(BACKEND) FAIL $$?"; exit 1);\
 	done
 
 clean:
